[build]
publish = "public"
command = "zola build --base-url https://zen-austin-0c80be.netlify.app"

[build.environment]
ZOLA_VERSION = "0.11.0"

[context.deploy-preview]
command = "zola build --base-url https://zen-austin-0c80be.netlify.app"